<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       DB::table('countries')->insert([
        ['symbol' => 'ABW', 'name' => 'Aruba'],
        ['symbol' => 'AFG', 'name' => 'Afghanistan'],
        ['symbol' => 'AGO', 'name' => 'Angola'],
        ['symbol' => 'AIA', 'name' => 'Anguilla'],
        ['symbol' => 'ALA', 'name' => 'Åland Islands'],
        ['symbol' => 'ALB', 'name' => 'Albania'],
        ['symbol' => 'AND', 'name' => 'Andorra'],
        ['symbol' => 'ARE', 'name' => 'United Arab Emirates'],
        ['symbol' => 'ARG', 'name' => 'Argentina'],
        ['symbol' => 'ARM', 'name' => 'Armenia'],
        ['symbol' => 'ASM', 'name' => 'American Samoa'],
        ['symbol' => 'ATA', 'name' => 'Antarctica'],
        ['symbol' => 'ATF', 'name' => 'French Southern Territories'],
        ['symbol' => 'ATG', 'name' => 'Antigua and Barbuda'],
        ['symbol' => 'AUS', 'name' => 'Australia'],
        ['symbol' => 'AUT', 'name' => 'Austria'],
        ['symbol' => 'AZE', 'name' => 'Azerbaijan'],
        ['symbol' => 'BDI', 'name' => 'Burundi'],
        ['symbol' => 'BEL', 'name' => 'Belgium'],
        ['symbol' => 'BEN', 'name' => 'Benin'],
        ['symbol' => 'BES', 'name' => 'Bonaire, Sint Eustatius and Saba'],
        ['symbol' => 'BFA', 'name' => 'Burkina Faso'],
        ['symbol' => 'BGD', 'name' => 'Bangladesh'],
        ['symbol' => 'BGR', 'name' => 'Bulgaria'],
        ['symbol' => 'BHR', 'name' => 'Bahrain'],
        ['symbol' => 'BHS', 'name' => 'Bahamas'],
        ['symbol' => 'BIH', 'name' => 'Bosnia and Herzegovina'],
        ['symbol' => 'BLM', 'name' => 'Saint Barthélemy'],
        ['symbol' => 'BLR', 'name' => 'Belarus'],
        ['symbol' => 'BLZ', 'name' => 'Belize'],
        ['symbol' => 'BMU', 'name' => 'Bermuda'],
        ['symbol' => 'BOL', 'name' => 'Bolivia, Plurinational State of'],
        ['symbol' => 'BRA', 'name' => 'Brazil'],
        ['symbol' => 'BRB', 'name' => 'Barbados'],
        ['symbol' => 'BRN', 'name' => 'Brunei Darussalam'],
        ['symbol' => 'BTN', 'name' => 'Bhutan'],
        ['symbol' => 'BVT', 'name' => 'Bouvet Island'],
        ['symbol' => 'BWA', 'name' => 'Botswana'],
        ['symbol' => 'CAF', 'name' => 'Central African Republic'],
        ['symbol' => 'CAN', 'name' => 'Canada'],
        ['symbol' => 'CCK', 'name' => 'Cocos (Keeling) Islands'],
        ['symbol' => 'CHE', 'name' => 'Switzerland'],
        ['symbol' => 'CHL', 'name' => 'Chile'],
        ['symbol' => 'CHN', 'name' => 'China'],
        ['symbol' => 'CIV', 'name' => 'Côte d\'Ivoire'],
        ['symbol' => 'CMR', 'name' => 'Cameroon'],
        ['symbol' => 'COD', 'name' => 'Congo, the Democratic Republic of the'],
        ['symbol' => 'COG', 'name' => 'Congo'],
        ['symbol' => 'COK', 'name' => 'Cook Islands'],
        ['symbol' => 'COL', 'name' => 'Colombia'],
        ['symbol' => 'COM', 'name' => 'Comoros'],
        ['symbol' => 'CPV', 'name' => 'Cape Verde'],
        ['symbol' => 'CRI', 'name' => 'Costa Rica'],
        ['symbol' => 'CUB', 'name' => 'Cuba'],
        ['symbol' => 'CUW', 'name' => 'Curaçao'],
        ['symbol' => 'CXR', 'name' => 'Christmas Island'],
        ['symbol' => 'CYM', 'name' => 'Cayman Islands'],
        ['symbol' => 'CYP', 'name' => 'Cyprus'],
        ['symbol' => 'CZE', 'name' => 'Czech Republic'],
        ['symbol' => 'DEU', 'name' => 'Germany'],
        ['symbol' => 'DJI', 'name' => 'Djibouti'],
        ['symbol' => 'DMA', 'name' => 'Dominica'],
        ['symbol' => 'DNK', 'name' => 'Denmark'],
        ['symbol' => 'DOM', 'name' => 'Dominican Republic'],
        ['symbol' => 'DZA', 'name' => 'Algeria'],
        ['symbol' => 'ECU', 'name' => 'Ecuador'],
        ['symbol' => 'EGY', 'name' => 'Egypt'],
        ['symbol' => 'ERI', 'name' => 'Eritrea'],
        ['symbol' => 'ESH', 'name' => 'Western Sahara'],
        ['symbol' => 'ESP', 'name' => 'Spain'],
        ['symbol' => 'EST', 'name' => 'Estonia'],
        ['symbol' => 'ETH', 'name' => 'Ethiopia'],
        ['symbol' => 'FIN', 'name' => 'Finland'],
        ['symbol' => 'FJI', 'name' => 'Fiji'],
        ['symbol' => 'FLK', 'name' => 'Falkland Islands (Malvinas)'],
        ['symbol' => 'FRA', 'name' => 'France'],
        ['symbol' => 'FRO', 'name' => 'Faroe Islands'],
        ['symbol' => 'FSM', 'name' => 'Micronesia, Federated States of'],
        ['symbol' => 'GAB', 'name' => 'Gabon'],
        ['symbol' => 'GBR', 'name' => 'United Kingdom'],
        ['symbol' => 'GEO', 'name' => 'Georgia'],
        ['symbol' => 'GGY', 'name' => 'Guernsey'],
        ['symbol' => 'GHA', 'name' => 'Ghana'],
        ['symbol' => 'GIB', 'name' => 'Gibraltar'],
        ['symbol' => 'GIN', 'name' => 'Guinea'],
        ['symbol' => 'GLP', 'name' => 'Guadeloupe'],
        ['symbol' => 'GMB', 'name' => 'Gambia'],
        ['symbol' => 'GNB', 'name' => 'Guinea-Bissau'],
        ['symbol' => 'GNQ', 'name' => 'Equatorial Guinea'],
        ['symbol' => 'GRC', 'name' => 'Greece'],
        ['symbol' => 'GRD', 'name' => 'Grenada'],
        ['symbol' => 'GRL', 'name' => 'Greenland'],
        ['symbol' => 'GTM', 'name' => 'Guatemala'],
        ['symbol' => 'GUF', 'name' => 'French Guiana'],
        ['symbol' => 'GUM', 'name' => 'Guam'],
        ['symbol' => 'GUY', 'name' => 'Guyana'],
        ['symbol' => 'HKG', 'name' => 'Hong Kong'],
        ['symbol' => 'HMD', 'name' => 'Heard Island and McDonald Islands'],
        ['symbol' => 'HND', 'name' => 'Honduras'],
        ['symbol' => 'HRV', 'name' => 'Croatia'],
        ['symbol' => 'HTI', 'name' => 'Haiti'],
        ['symbol' => 'HUN', 'name' => 'Hungary'],
        ['symbol' => 'IDN', 'name' => 'Indonesia'],
        ['symbol' => 'IMN', 'name' => 'Isle of Man'],
        ['symbol' => 'IND', 'name' => 'India'],
        ['symbol' => 'IOT', 'name' => 'British Indian Ocean Territory'],
        ['symbol' => 'IRL', 'name' => 'Ireland'],
        ['symbol' => 'IRN', 'name' => 'Iran, Islamic Republic of'],
        ['symbol' => 'IRQ', 'name' => 'Iraq'],
        ['symbol' => 'ISL', 'name' => 'Iceland'],
        ['symbol' => 'ISR', 'name' => 'Israel'],
        ['symbol' => 'ITA', 'name' => 'Italy'],
        ['symbol' => 'JAM', 'name' => 'Jamaica'],
        ['symbol' => 'JEY', 'name' => 'Jersey'],
        ['symbol' => 'JOR', 'name' => 'Jordan'],
        ['symbol' => 'JPN', 'name' => 'Japan'],
        ['symbol' => 'KAZ', 'name' => 'Kazakhstan'],
        ['symbol' => 'KEN', 'name' => 'Kenya'],
        ['symbol' => 'KGZ', 'name' => 'Kyrgyzstan'],
        ['symbol' => 'KHM', 'name' => 'Cambodia'],
        ['symbol' => 'KIR', 'name' => 'Kiribati'],
        ['symbol' => 'KNA', 'name' => 'Saint Kitts and Nevis'],
        ['symbol' => 'KOR', 'name' => 'Korea, Republic of'],
        ['symbol' => 'KWT', 'name' => 'Kuwait'],
        ['symbol' => 'LAO', 'name' => 'Lao People\'s Democratic Republic'],
        ['symbol' => 'LBN', 'name' => 'Lebanon'],
        ['symbol' => 'LBR', 'name' => 'Liberia'],
        ['symbol' => 'LBY', 'name' => 'Libya'],
        ['symbol' => 'LCA', 'name' => 'Saint Lucia'],
        ['symbol' => 'LIE', 'name' => 'Liechtenstein'],
        ['symbol' => 'LKA', 'name' => 'Sri Lanka'],
        ['symbol' => 'LSO', 'name' => 'Lesotho'],
        ['symbol' => 'LTU', 'name' => 'Lithuania'],
        ['symbol' => 'LUX', 'name' => 'Luxembourg'],
        ['symbol' => 'LVA', 'name' => 'Latvia'],
        ['symbol' => 'MAC', 'name' => 'Macao'],
        ['symbol' => 'MAF', 'name' => 'Saint Martin (French part)'],
        ['symbol' => 'MAR', 'name' => 'Morocco'],
        ['symbol' => 'MCO', 'name' => 'Monaco'],
        ['symbol' => 'MDA', 'name' => 'Moldova, Republic of'],
        ['symbol' => 'MDG', 'name' => 'Madagascar'],
        ['symbol' => 'MDV', 'name' => 'Maldives'],
        ['symbol' => 'MEX', 'name' => 'Mexico'],
        ['symbol' => 'MHL', 'name' => 'Marshall Islands'],
        ['symbol' => 'MKD', 'name' => 'Macedonia, the former Yugoslav Republic of'],
        ['symbol' => 'MLI', 'name' => 'Mali'],
        ['symbol' => 'MLT', 'name' => 'Malta'],
        ['symbol' => 'MMR', 'name' => 'Myanmar'],
        ['symbol' => 'MNE', 'name' => 'Montenegro'],
        ['symbol' => 'MNG', 'name' => 'Mongolia'],
        ['symbol' => 'MNP', 'name' => 'Northern Mariana Islands'],
        ['symbol' => 'MOZ', 'name' => 'Mozambique'],
        ['symbol' => 'MRT', 'name' => 'Mauritania'],
        ['symbol' => 'MSR', 'name' => 'Montserrat'],
        ['symbol' => 'MTQ', 'name' => 'Martinique'],
        ['symbol' => 'MUS', 'name' => 'Mauritius'],
        ['symbol' => 'MWI', 'name' => 'Malawi'],
        ['symbol' => 'MYS', 'name' => 'Malaysia'],
        ['symbol' => 'MYT', 'name' => 'Mayotte'],
        ['symbol' => 'NAM', 'name' => 'Namibia'],
        ['symbol' => 'NCL', 'name' => 'New Caledonia'],
        ['symbol' => 'NER', 'name' => 'Niger'],
        ['symbol' => 'NFK', 'name' => 'Norfolk Island'],
        ['symbol' => 'NGA', 'name' => 'Nigeria'],
        ['symbol' => 'NIC', 'name' => 'Nicaragua'],
        ['symbol' => 'NIU', 'name' => 'Niue'],
        ['symbol' => 'NLD', 'name' => 'Netherlands'],
        ['symbol' => 'NOR', 'name' => 'Norway'],
        ['symbol' => 'NPL', 'name' => 'Nepal'],
        ['symbol' => 'NRU', 'name' => 'Nauru'],
        ['symbol' => 'NZL', 'name' => 'New Zealand'],
        ['symbol' => 'OMN', 'name' => 'Oman'],
        ['symbol' => 'PAK', 'name' => 'Pakistan'],
        ['symbol' => 'PAN', 'name' => 'Panama'],
        ['symbol' => 'PCN', 'name' => 'Pitcairn'],
        ['symbol' => 'PER', 'name' => 'Peru'],
        ['symbol' => 'PHL', 'name' => 'Philippines'],
        ['symbol' => 'PLW', 'name' => 'Palau'],
        ['symbol' => 'PNG', 'name' => 'Papua New Guinea'],
        ['symbol' => 'POL', 'name' => 'Poland'],
        ['symbol' => 'PRI', 'name' => 'Puerto Rico'],
        ['symbol' => 'PRK', 'name' => 'Korea, Democratic People\'s Republic of'],
        ['symbol' => 'PRT', 'name' => 'Portugal'],
        ['symbol' => 'PRY', 'name' => 'Paraguay'],
        ['symbol' => 'PSE', 'name' => 'Palestinian Territory, Occupied'],
        ['symbol' => 'PYF', 'name' => 'French Polynesia'],
        ['symbol' => 'QAT', 'name' => 'Qatar'],
        ['symbol' => 'REU', 'name' => 'Réunion'],
        ['symbol' => 'ROU', 'name' => 'Romania'],
        ['symbol' => 'RUS', 'name' => 'Russian Federation'],
        ['symbol' => 'RWA', 'name' => 'Rwanda'],
        ['symbol' => 'SAU', 'name' => 'Saudi Arabia'],
        ['symbol' => 'SDN', 'name' => 'Sudan'],
        ['symbol' => 'SEN', 'name' => 'Senegal'],
        ['symbol' => 'SGP', 'name' => 'Singapore'],
        ['symbol' => 'SGS', 'name' => 'South Georgia and the South Sandwich Islands'],
        ['symbol' => 'SHN', 'name' => 'Saint Helena, Ascension and Tristan da Cunha'],
        ['symbol' => 'SJM', 'name' => 'Svalbard and Jan Mayen'],
        ['symbol' => 'SLB', 'name' => 'Solomon Islands'],
        ['symbol' => 'SLE', 'name' => 'Sierra Leone'],
        ['symbol' => 'SLV', 'name' => 'El Salvador'],
        ['symbol' => 'SMR', 'name' => 'San Marino'],
        ['symbol' => 'SOM', 'name' => 'Somalia'],
        ['symbol' => 'SPM', 'name' => 'Saint Pierre and Miquelon'],
        ['symbol' => 'SRB', 'name' => 'Serbia'],
        ['symbol' => 'SSD', 'name' => 'South Sudan'],
        ['symbol' => 'STP', 'name' => 'Sao Tome and Principe'],
        ['symbol' => 'SUR', 'name' => 'Suriname'],
        ['symbol' => 'SVK', 'name' => 'Slovakia'],
        ['symbol' => 'SVN', 'name' => 'Slovenia'],
        ['symbol' => 'SWE', 'name' => 'Sweden'],
        ['symbol' => 'SWZ', 'name' => 'Swaziland'],
        ['symbol' => 'SXM', 'name' => 'Sint Maarten (Dutch part)'],
        ['symbol' => 'SYC', 'name' => 'Seychelles'],
        ['symbol' => 'SYR', 'name' => 'Syrian Arab Republic'],
        ['symbol' => 'TCA', 'name' => 'Turks and Caicos Islands'],
        ['symbol' => 'TCD', 'name' => 'Chad'],
        ['symbol' => 'TGO', 'name' => 'Togo'],
        ['symbol' => 'THA', 'name' => 'Thailand'],
        ['symbol' => 'TJK', 'name' => 'Tajikistan'],
        ['symbol' => 'TKL', 'name' => 'Tokelau'],
        ['symbol' => 'TKM', 'name' => 'Turkmenistan'],
        ['symbol' => 'TLS', 'name' => 'Timor-Leste'],
        ['symbol' => 'TON', 'name' => 'Tonga'],
        ['symbol' => 'TTO', 'name' => 'Trinidad and Tobago'],
        ['symbol' => 'TUN', 'name' => 'Tunisia'],
        ['symbol' => 'TUR', 'name' => 'Turkey'],
        ['symbol' => 'TUV', 'name' => 'Tuvalu'],
        ['symbol' => 'TWN', 'name' => 'Taiwan, Province of China'],
        ['symbol' => 'TZA', 'name' => 'Tanzania, United Republic of'],
        ['symbol' => 'UGA', 'name' => 'Uganda'],
        ['symbol' => 'UKR', 'name' => 'Ukraine'],
        ['symbol' => 'UMI', 'name' => 'United States Minor Outlying Islands'],
        ['symbol' => 'URY', 'name' => 'Uruguay'],
        ['symbol' => 'USA', 'name' => 'United States'],
        ['symbol' => 'UZB', 'name' => 'Uzbekistan'],
        ['symbol' => 'VAT', 'name' => 'Holy See (Vatican City State)'],
        ['symbol' => 'VCT', 'name' => 'Saint Vincent and the Grenadines'],
        ['symbol' => 'VEN', 'name' => 'Venezuela, Bolivarian Republic of'],
        ['symbol' => 'VGB', 'name' => 'Virgin Islands, British'],
        ['symbol' => 'VIR', 'name' => 'Virgin Islands, U.S.'],
        ['symbol' => 'VNM', 'name' => 'Viet Nam'],
        ['symbol' => 'VUT', 'name' => 'Vanuatu'],
        ['symbol' => 'WLF', 'name' => 'Wallis and Futuna'],
        ['symbol' => 'WSM', 'name' => 'Samoa'],
        ['symbol' => 'YEM', 'name' => 'Yemen'],
        ['symbol' => 'ZAF', 'name' => 'South Africa'],
        ['symbol' => 'ZMB', 'name' => 'Zambia'],
        ['symbol' => 'ZWE', 'name' => 'Zimbabwe'],
       ]);
    }
}
